// projects/create-react-app/files/src/App.js
import './App.css';

import { CdsDivider } from "@cds/react/divider"

function App() {
  return (
    <div className="App">
        <header className="header header-6">
          <div className="branding">
            <a
              href="https://clarity.design"
              target="_blank"
              rel="noreferrer"
              aria-current="page"
              >
              <img
                className="logo"
                alt="Clarity Design System"
                src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' height='36' viewBox='0 0 36 36' width='36'%3E%3Cg fill='none' fill-rule='evenodd' transform='translate(0 4.544118)'%3E%3Cpath d='m24.7018129.03888403 11.2778281 6.67879663-.0181821 13.56348904-11.259646 6.6606051-6.6844666-3.9709902 11.6514714-6.541272v-5.8973849l-4.7471673-2.60470586-6.8895427-3.93711399' fill='%230095d3'/%3E%3Cpath d='m11.3313965.03888403-11.277828 6.67879663.01818205 13.56348904 11.25964595 6.6606051 6.6852924-3.9717138-10.66220196-6.5405484v-5.8973849l10.67797726-6.54221107' fill='%23f38b00'/%3E%3Cpath d='m18.017374 22.9708988-6.5183252-3.998915 6.5222007-3.8447451 6.9298332 3.951391' fill='%23004b70'/%3E%3Cpath d='m18.0314053 3.98921729-6.5046536 3.98442963 6.5172421 3.88418548 6.8619013-3.93951296' fill='%2398441e'/%3E%3C/g%3E%3C/svg%3E"
                type="image/svg+xml"
              />
              <span className="title">Clarity Design System</span>
            </a>
          </div>
        </header>

        <div cds-layout="grid gap:md gap@md:xl p:lg p@sm:xl p-y@lg:xxl container:xl container:center">
          <div cds-layout="vertical gap:lg gap@md:xl col@sm:7">
            <h3 cds-text="display">
              Create React App Starter
            </h3>
            <p cds-text="message">
              Edit <code>src/App.js</code> and save to reload.
            </p>
          </div>
        </div>

        <CdsDivider />
        <footer className="demo-footer" cds-layout="p:md p@md:lg">
          Demo application for <a href="https://clarity.design">Clarity Design</a>
        </footer>
    </div>
  );
}

export default App;

// projects/angular-cli/files/src/app/app.component.ts
import { Component } from '@angular/core';

import '@cds/core/divider/register.js';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {}

<header class="header header-6">
  <div class="branding">
    <a
      href="https://clarity.design"
      target="_blank"
      rel="noreferrer"
      aria-current="page"
      >
      <img
        class="logo"
        alt="Clarity Design System"
        src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' height='36' viewBox='0 0 36 36' width='36'%3E%3Cg fill='none' fill-rule='evenodd' transform='translate(0 4.544118)'%3E%3Cpath d='m24.7018129.03888403 11.2778281 6.67879663-.0181821 13.56348904-11.259646 6.6606051-6.6844666-3.9709902 11.6514714-6.541272v-5.8973849l-4.7471673-2.60470586-6.8895427-3.93711399' fill='%230095d3'/%3E%3Cpath d='m11.3313965.03888403-11.277828 6.67879663.01818205 13.56348904 11.25964595 6.6606051 6.6852924-3.9717138-10.66220196-6.5405484v-5.8973849l10.67797726-6.54221107' fill='%23f38b00'/%3E%3Cpath d='m18.017374 22.9708988-6.5183252-3.998915 6.5222007-3.8447451 6.9298332 3.951391' fill='%23004b70'/%3E%3Cpath d='m18.0314053 3.98921729-6.5046536 3.98442963 6.5172421 3.88418548 6.8619013-3.93951296' fill='%2398441e'/%3E%3C/g%3E%3C/svg%3E"
        type="image/svg+xml"
      />
      <span class="title">Clarity Design System</span>
    </a>
  </div>
</header>

<div cds-layout="grid gap:md gap@md:xl p:lg p@sm:xl p-y@lg:xxl container:xl container:center">
  <div cds-layout="vertical gap:lg gap@md:xl col@sm:7">
    <h3 cds-text="display">
      Create Angular App Starter
    </h3>
    <p cds-text="message">
      Edit <code>src/app/app.component.ts</code> and save to reload.
    </p>
  </div>
</div>

<cds-divider></cds-divider>
<footer class="demo-footer" cds-layout="p:md p@md:lg">
  Demo application for <a href="https://clarity.design">Clarity Design</a>
</footer>
